### ISSUE TITLE
Error while trying to set text of question TextArea

### ISSUE THREAD

**Issue by idangur** [fc1018/BardBoost#1]
Uncaught (in promise) TypeError: Cannot set properties of null (setting 'textContent')
    at queryEntry (<anonymous>:4:20)
    at <anonymous>:23:20
    
From the console logs

**Comment by fc1018** [comment]
I updated the script very recently because of Google Bard allowing mic input, can you verify you have the latest version in your boost?

If you do have the latest version, this error can be when the script runs without the webpage fully loading and has given me lots of problems in the past, hence setting the timeout to 100ms. It's possible that if your internet connection is slower the javascript might run without the page being fully loaded.

Try replacing line 23 with:

`setTimeout(()=> queryEntry(question), 200)`

and let me know if that fixes it!

**Comment by DovRosman** [comment]
I have the same problem, it didn't fix it. 
I got this message in my console, maybe that's relevant? 

`[Deprecation] Listener added for a synchronous 'DOMNodeInserted' DOM Mutation Event. This event type is deprecated (https://w3c.github.io/uievents/#legacy-event-types) and work is underway to remove it from this browser. Usage of this event listener will cause performance issues today, and represents a risk of future incompatibility. Consider using MutationObserver instead.`

**Comment by fc1018** [comment]
It's possible that Google Bard looks different in your country compared to mine (UK), can you try running `document.querySelector("rich-textarea > * > p");` in your console and tell me what you get?

**Comment by DovRosman** [comment]
![image](https://github.com/fc1018/BardBoost/assets/105514454/50964338-b2ec-4cd8-a930-bc6b28b8c18a)
I got this in the US. Does it mean anything?

**Comment by fc1018** [comment]
Okay so that means that it has found the text box, which is good! Now can you enter into the console:
`document.querySelector("rich-textarea > * > p").textContent = "You should see this sentence in the text box"`

If you see the sentence in your entry field then I'm not sure where the error stems from because the original error:

> Uncaught (in promise) TypeError: Cannot set properties of null (setting 'textContent')
>at queryEntry (:4:20)
>at :23:20

means that the script couldn't find the text box as it appears as null instead of the `<p> <br> </p>`.

**Comment by DovRosman** [comment]
The text appeared in the box, so I'm not sure what the problem could be. I'm assuming it has something to do with taking the prompt from the URL but I'm not good enough with JS to figure out how to fix it.

**Comment by fc1018** [comment]
Interesting.

You can manually perform all the functions of the script if you want by doing this order of commands into the console:
`document.querySelector("rich-textarea > * > p").textContent = "Question grabbed from URL"`
`document.querySelector("input-area > div > div:nth-child(4) > button").click()`

Expected output is "Question grabbed by URL" being sent to bard.

**Comment by DovRosman** [comment]
I got that output, any other ideas?

**Comment by fc1018** [comment]
I would follow the set up steps again to make sure everything is set up correctly and if it still gives the same error I would try another device with Arc to see whether the same problem occurs (if that is possible).

**Comment by DovRosman** [comment]
I re set it up, still doesn't work. I don't have any other devices with Arc.

**Comment by fc1018** [comment]
If possible can you show me screenshots of you putting the query through search and bard after that as well as the console?

**Comment by DovRosman** [comment]
cmd + t and writing bard
<img width="1552" alt="Screenshot 2024-01-26 at 4 00 50 PM" src="https://github.com/fc1018/BardBoost/assets/105514454/fca0d74f-042e-406f-ac45-9385c04d7417">

Hitting tab and the prompt
<img width="1552" alt="Screenshot 2024-01-26 at 4 01 06 PM" src="https://github.com/fc1018/BardBoost/assets/105514454/87f858b3-49e1-402e-9153-106959eab3ac">

End result when I hit enter
<img width="1552" alt="Screenshot 2024-01-26 at 4 01 10 PM" src="https://github.com/fc1018/BardBoost/assets/105514454/8c42d9b8-fbe8-49b5-aec3-691585d506be">

**Comment by fc1018** [comment]
Can I get a screenshot of the console after you press enter?

**Comment by idangur** [comment]
I will share as well tomorrow, thanks !

**Comment by DovRosman** [comment]
@fc1018 I don't think I changed anything in the code, but today it's working when it wasn't yesterday. I think it has something to do with my updating Arc since I was running the version from about a month ago.
